#!/usr/bin/env node
/**
 * forge-app-design scaffold tool
 *
 * 一键吐确定层：package.json / next config / api routes / mock data / app/layout
 * + 每个 page 的空 placeholder（等 LLM 后续 Write 业务拼装）。
 *
 * NOT does: 视觉拼装（broken composer 已废弃，由 LLM 直接看 forge cases/ 真示例自己写）。
 *
 * Usage:
 *   node scaffold.mjs \
 *     --name "<app-slug>" \
 *     --entities-json '[{"name":"Customer","fields":[...]},...]' \
 *     --pages-json '[{"id":"customer-list","route":"/customers","layout":"list-with-drawer","primaryEntity":"Customer","title":"客户管理"},...]' \
 *     [--domain "CRM"] [--output ./output/<name>] [--forge-repo <path>] [--with-auth]
 */

import { parseArgs } from 'node:util'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── CLI args ─────────────────────────────────────────────────────────────────

const { values } = parseArgs({
  options: {
    name: { type: 'string' },
    'entities-json': { type: 'string' },
    'pages-json': { type: 'string' },
    domain: { type: 'string', default: 'Other' },
    output: { type: 'string' },
    'forge-repo': { type: 'string' },
    'with-auth': { type: 'boolean', default: false },
  },
})

if (!values.name || !values['entities-json'] || !values['pages-json']) {
  process.stderr.write(
    'Usage: scaffold.mjs --name <slug> --entities-json <json> --pages-json <json> [--domain X] [--output ./output/X] [--forge-repo <path>] [--with-auth]\n',
  )
  process.exit(1)
}

let entities, pages
try {
  entities = JSON.parse(values['entities-json'])
  pages = JSON.parse(values['pages-json'])
} catch (err) {
  process.stderr.write(`Invalid JSON in --entities-json or --pages-json: ${err.message}\n`)
  process.exit(2)
}

if (!Array.isArray(entities) || entities.length === 0) {
  process.stderr.write('entities-json must be a non-empty array\n')
  process.exit(2)
}
if (!Array.isArray(pages) || pages.length === 0) {
  process.stderr.write('pages-json must be a non-empty array\n')
  process.exit(2)
}

const outputDir = values.output || `./output/${values.name}`
const forgeRepo = resolveForgeRepo(values['forge-repo'])

const appIR = {
  appName: values.name,
  appLabel: displayLabel(values.name),
  domain: values.domain,
  description: `${values.name}: generated by forge-app-design skill`,
  entities,
  pages,
  auth: {
    required: values['with-auth'],
    strategy: 'mock',
    loginRoute: '/login',
    defaultRedirect: pages[0]?.route ?? '/',
  },
  mockData: { rowsPerEntity: 20 },
}

function displayLabel(name) {
  const stop = new Set(['codex', 'sonnet', 'opus', 'spark', 'demo'])
  const words = String(name)
    .split(/[-_\s]+/)
    .filter(Boolean)
    .filter(word => !/^c\d+[a-z]?$/i.test(word))
    .filter(word => !/^v\d+$/i.test(word))
    .filter(word => !stop.has(word.toLowerCase()))

  const twoWordLabel = words
    .slice(0, 2)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')

  if (twoWordLabel && twoWordLabel.length <= 12) return twoWordLabel

  const firstWord = words[0]
    ? words[0].charAt(0).toUpperCase() + words[0].slice(1)
    : ''
  if (firstWord && firstWord.length <= 12) return firstWord

  const acronym = words.slice(0, 3).map(word => word.charAt(0).toUpperCase()).join('')
  return acronym || name
}

function isSidebarNavigationPage(page) {
  if (page?.surfaceRole) return page.surfaceRole === 'navigation'

  const route = String(page?.route ?? '')
  if (!route || route.includes('[') || route.includes('/:')) return false

  const segments = route.split('/').filter(Boolean)
  const leaf = segments.at(-1)?.toLowerCase()
  if (['new', 'create', 'edit', 'import', 'export', 'bulk'].includes(leaf)) return false

  return page?.layout !== 'wizard' && page?.routeRole !== 'wizard'
}

// ── Deterministic scaffold layer ─────────────────────────────────────────────

mkdirSync(outputDir, { recursive: true })

writePackageJson(outputDir, appIR)
writeNextConfig(outputDir)
writeTsConfig(outputDir)
writePostcssConfig(outputDir)
writeTailwindConfig(outputDir)
writeGitignore(outputDir)
writeReadme(outputDir, appIR)
writeGlobalsCss(outputDir)
writeAppShell({ ...appIR, pages: appIR.pages.filter(isSidebarNavigationPage) }, outputDir)
writeMockData(appIR, outputDir)

// ── Custom: page placeholders ────────────────────────────────────────────────

function writeNextConfig(outputDir) {
  writeFileSync(
    join(outputDir, 'next.config.ts'),
    `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  transpilePackages: ['@forge-ui-official/core'],
}

export default nextConfig
`,
    'utf8',
  )
}

function writePackageJson(outputDir, appIR) {
  const forgeCorePath = join(forgeRepo, 'core').split('\\').join('/')
  writeFileSync(join(outputDir, 'package.json'), JSON.stringify({
    name: appIR.appName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      '@forge-ui-official/core': `file:${forgeCorePath}`,
      next: '16.2.2',
      react: '19.2.4',
      'react-dom': '19.2.4',
      'solar-icon-set': '^2.0.1',
    },
    devDependencies: {
      '@tailwindcss/postcss': '^4',
      '@types/node': '^20',
      '@types/react': '^19',
      '@types/react-dom': '^19',
      tailwindcss: '^4',
      typescript: '^5.1.0',
    },
  }, null, 2) + '\n', 'utf8')
}

function resolveForgeRepo(explicitPath) {
  const candidates = [
    explicitPath,
    process.env.FORGE_REPO,
    process.env.FORGE_UI_REPO,
    findNearestForgeRepo(__dirname),
    findNearestForgeRepo(process.cwd()),
  ].filter(Boolean)

  for (const candidate of candidates) {
    const resolved = resolve(candidate)
    if (isForgeRepo(resolved)) return resolved
  }

  process.stderr.write([
    'Unable to locate the Forge repo root.',
    'Pass --forge-repo <path> or set FORGE_REPO to a directory containing core/package.json.',
  ].join('\n') + '\n')
  process.exit(2)
}

function findNearestForgeRepo(startDir) {
  let current = resolve(startDir)
  while (true) {
    if (isForgeRepo(current)) return current
    const parent = dirname(current)
    if (parent === current) return null
    current = parent
  }
}

function isForgeRepo(dir) {
  return existsSync(join(dir, 'core', 'package.json'))
}

function writeTsConfig(outputDir) {
  writeFileSync(join(outputDir, 'tsconfig.json'), JSON.stringify({
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'react-jsx',
      incremental: true,
      plugins: [{ name: 'next' }],
      baseUrl: '.',
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts', '.next/dev/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2) + '\n', 'utf8')
}

function writePostcssConfig(outputDir) {
  writeFileSync(join(outputDir, 'postcss.config.mjs'), `const config = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
}

export default config
`, 'utf8')
}

function writeTailwindConfig(outputDir) {
  writeFileSync(join(outputDir, 'tailwind.config.ts'), `export default {
  content: [
    './app/**/*.{ts,tsx}',
    './node_modules/@forge-ui-official/core/dist/**/*.{js,mjs,ts,tsx}',
  ],
}
`, 'utf8')
}

function writeGitignore(outputDir) {
  writeFileSync(join(outputDir, '.gitignore'), `.next
node_modules
*.log
`, 'utf8')
}

function writeReadme(outputDir, appIR) {
  writeFileSync(join(outputDir, 'README.md'), `# ${appIR.appLabel}

Generated by forge-app-design.

## Run

\`\`\`bash
pnpm install --ignore-workspace --ignore-scripts
pnpm build
pnpm dev
\`\`\`
`, 'utf8')
}

function writeGlobalsCss(outputDir) {
  const appDir = join(outputDir, 'app')
  mkdirSync(appDir, { recursive: true })
  writeFileSync(join(appDir, 'globals.css'), `@import "tailwindcss" source("../app");
@import "@forge-ui-official/core/styles.css";

/* Scan Forge core dist so fg-* utility classes are included in output CSS. */
@source "../node_modules/@forge-ui-official/core/dist";

/* Keep generated admin patterns responsive even when the app is created under ignored tmp output paths. */
@source inline("sm:grid-cols-2 md:grid-cols-2 md:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 lg:grid-cols-12 xl:grid-cols-2 xl:grid-cols-4");
@source inline("xl:grid-cols-[minmax(12rem,16rem)_minmax(0,1fr)_minmax(0,1fr)]");
@source inline("xl:grid-cols-[minmax(0,1fr)_minmax(20rem,24rem)]");
@source inline("sm:grid-cols-[minmax(0,1fr)_minmax(10rem,14rem)]");
@source inline("2xl:grid-cols-[minmax(0,1fr)_clamp(18rem,24vw,24rem)]");
@source inline("lg:col-span-2 lg:col-span-3 lg:col-span-4 lg:col-span-6 lg:col-span-8 lg:col-span-9 lg:col-span-10 xl:col-span-3 xl:col-span-4 xl:col-span-8");
@source inline("lg:flex-row lg:flex-wrap lg:flex-nowrap lg:items-end lg:justify-between lg:p-5");
@source inline("xl:flex-row xl:items-center xl:justify-between md:col-span-2");
@source inline("[&_td]:px-3 [&_td]:py-2 [&_th]:px-3 [&_th]:py-2 [&_td]:px-4 [&_td]:py-3 [&_th]:px-4 [&_th]:py-3");
@source inline("w-[clamp(5.5rem,8vw,7rem)] w-[clamp(6rem,9vw,8rem)] w-[clamp(7rem,12vw,10rem)] w-[clamp(8rem,11vw,10rem)] w-[clamp(10rem,18vw,14rem)] w-[clamp(13rem,24vw,17rem)] w-[clamp(14rem,24vw,20rem)]");
`, 'utf8')
}

function writeAppShell(appIR, outputDir) {
  const appDir = join(outputDir, 'app')
  mkdirSync(appDir, { recursive: true })
  const menuJson = JSON.stringify(appIR.pages.map(page => ({
    label: page.title || page.id || page.route,
    href: page.route,
  })), null, 2)
  const profileName = domainProfileName(appIR.domain)
  const profileRole = `${displayLabel(appIR.domain ?? 'Ops')} Lead`

  writeFileSync(join(appDir, 'layout.tsx'), `import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { AppLayout } from '@forge-ui-official/core'
import type { AppLayoutMenuItem } from '@forge-ui-official/core'
import './globals.css'

export const metadata: Metadata = {
  title: '${escapeTsString(appIR.appLabel)}',
  description: '${escapeTsString(appIR.description ?? appIR.appLabel)}',
}

const MENU_ITEMS: AppLayoutMenuItem[] = ${menuJson}

const PROFILE = {
  avatar: 'https://i.pravatar.cc/150?u=${escapeTsString(appIR.appName)}-owner',
  name: '${profileName}',
  role: '${escapeTsString(profileRole)}',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppLayout
          mode="light"
          accent="purple"
          logoText="${escapeTsString(appIR.appLabel)}"
          menuItems={MENU_ITEMS}
          profilePosition="topbar"
          profile={PROFILE}
          teamName="${escapeTsString(appIR.appLabel)}"
          teamAvatar="https://i.pravatar.cc/150?u=${escapeTsString(appIR.appName)}-team"
          teamMemberCount={8}
          notifications={7}
          messages={3}
        >
          {children}
        </AppLayout>
      </body>
    </html>
  )
}
`, 'utf8')
}

function domainProfileName(domain) {
  const text = String(domain ?? '').toLowerCase()
  if (/finance|billing|invoice|revenue/.test(text)) return 'Nora Lee'
  if (/support|ticket|service/.test(text)) return 'Owen Patel'
  if (/sales|crm|customer/.test(text)) return 'Priya Shah'
  if (/compliance|risk|policy|vendor/.test(text)) return 'Maya Chen'
  return 'Alex Morgan'
}

function escapeTsString(value) {
  return String(value ?? '').replaceAll('\\', '\\\\').replaceAll("'", "\\'")
}

function writeMockData(appIR, outputDir) {
  const mockDir = join(outputDir, 'mock')
  mkdirSync(mockDir, { recursive: true })

  for (const entity of appIR.entities) {
    const fileName = `${toKebabCase(entity.name)}.ts`
    writeFileSync(join(mockDir, fileName), mockEntityContent(entity), 'utf8')
  }

  writeFileSync(
    join(mockDir, 'index.ts'),
    appIR.entities.map(entity => `export * from './${toKebabCase(entity.name)}'`).join('\n') + '\n',
    'utf8',
  )
}

function mockEntityContent(entity) {
  const typeName = entity.name
  const crud = crudHelperName(entity)
  const fields = Array.isArray(entity.fields) ? entity.fields : []
  const rows = Array.from({ length: 12 }, (_item, index) => mockRow(entity, index))
  const fieldLines = fields.map(field => `  ${field.key}: ${fieldTsType(field)}`).join('\n')

  return `export interface ${typeName} {
  id: string
${fieldLines}
}

const initialRows: ${typeName}[] = ${JSON.stringify(rows, null, 2)}

let rows = [...initialRows]

export const ${crud} = {
  async list() {
    return rows
  },
  async get(id: string) {
    return rows.find(item => item.id === id) ?? null
  },
  async create(input: Partial<${typeName}>) {
    const item = { ...initialRows[0], ...input, id: input.id ?? \`${entityPrefix(entity.name)}-\${Date.now()}\` } as ${typeName}
    rows = [item, ...rows]
    return item
  },
  async update(id: string, input: Partial<${typeName}>) {
    let updated: ${typeName} | null = null
    rows = rows.map(item => {
      if (item.id !== id) return item
      updated = { ...item, ...input }
      return updated
    })
    return updated
  },
  async remove(id: string) {
    const before = rows.length
    rows = rows.filter(item => item.id !== id)
    return rows.length !== before
  },
}
`
}

function fieldTsType(field) {
  if (field?.type === 'number') return 'number'
  if (field?.type === 'boolean') return 'boolean'
  return 'string'
}

function mockRow(entity, index) {
  const row = { id: `${entityPrefix(entity.name)}-${String(1001 + index)}` }
  for (const field of entity.fields ?? []) {
    if (!field?.key) continue
    row[field.key] = mockValue(entity, field, index)
  }
  return row
}

function mockValue(entity, field, index) {
  const key = String(field.key)
  const lower = key.toLowerCase()
  const options = Array.isArray(field.options) && field.options.length ? field.options : null

  if (field.type === 'enum' && options) return options[index % options.length]
  if (field.type === 'number') {
    if (/risk|score|readiness|progress|percent|rate/.test(lower)) return [91, 78, 63, 52, 38, 84][index % 6]
    if (/amount|exposure|value|revenue|price|cost|total/.test(lower)) return [1180000, 740000, 510000, 185000, 96000, 420000][index % 6]
    return index + 1
  }
  if (field.type === 'boolean') return index % 2 === 0
  if (field.type === 'date') return `2026-06-${String(5 + (index % 20)).padStart(2, '0')}`
  if (field.type === 'ref') return `${entityPrefix(field.target ?? 'ref')}-${String(1001 + (index % 6))}`

  if (/name|title/.test(lower)) return `${displayLabel(entity.name)} ${index + 1}`
  if (/owner|assignee|reviewer|controller|manager/.test(lower)) return ['Maya Chen', 'Priya Shah', 'Daniel Kim', 'Elena Torres', 'Owen Patel', 'Nora Lee'][index % 6]
  if (/email/.test(lower)) return `user${index + 1}@example.com`
  if (/phone|mobile/.test(lower)) return `+1 415 555 ${String(1000 + index)}`
  if (/status/.test(lower)) return options ? options[index % options.length] : ['Active', 'Under Review', 'Blocked', 'Ready'][index % 4]
  if (/category|type|segment|tier/.test(lower)) return options ? options[index % options.length] : ['Enterprise', 'Mid-market', 'SMB', 'Internal'][index % 4]
  if (/reason|cause|summary|note|description|impact|action/.test(lower)) return [
    'Evidence packet requires owner review before release.',
    'Policy exception needs approval before the next workflow step.',
    'Finance exposure remains at risk until the blocker is cleared.',
    'Related records should be checked before escalation.',
  ][index % 4]

  return `${displayLabel(entity.name)} ${key} ${index + 1}`
}

function entityPrefix(name) {
  return String(name)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map(part => part[0])
    .join('')
    .toUpperCase()
    .slice(0, 4) || 'ID'
}

function routeToFsPath(route) {
  return String(route).replace(/^\//, '')
}

function placeholderContent(page) {
  return `// PLACEHOLDER: forge-app-design skill expects real forge component composition.
//
// To compose this page, the LLM should:
//   1. Read forge/src/app/cases/<table|list|card|page-header|filter|chart|...>/page.tsx
//      for real component usage examples.
//   2. Verify component props against Forge core source or local docs.
//   3. Write a real implementation here, fetching data from /api/<entity-kebab>.
'use client'

import React from 'react'

export default function Page() {
  return (
    <main className="min-h-screen bg-fg-grey-50 p-8">
      <div className="rounded-card border border-dashed border-fg-grey-300 bg-white p-12 text-center">
        <h1 className="text-xl font-semibold text-fg-grey-900">
          ⚠️ ${page.title || page.id}
        </h1>
        <p className="mt-2 text-sm text-fg-grey-600">
          Placeholder (layout: <code className="rounded bg-fg-grey-100 px-1.5 py-0.5">${page.layout}</code>${page.primaryEntity ? `, entity: <code className=\"rounded bg-fg-grey-100 px-1.5 py-0.5\">${page.primaryEntity}</code>` : ''})
        </p>
        <p className="mt-1 text-xs text-fg-grey-500">
          Awaiting LLM authoring. Refer to forge/src/app/cases/ for real component examples.
        </p>
      </div>
    </main>
  )
}
`
}

for (const page of pages) {
  const fsPath = routeToFsPath(page.route)
  const pageDir = join(outputDir, 'app', fsPath)
  mkdirSync(pageDir, { recursive: true })
  writeFileSync(join(pageDir, 'page.tsx'), placeholderContent(page), 'utf8')
}

// ── Custom: in-memory CRUD API routes per entity ─────────────────────────────

/**
 * PascalCase → kebab-case, handling acronyms correctly.
 *   CustomerAccount → customer-account
 *   SLAPolicy       → sla-policy       (not s-l-a-policy)
 *   APIKey          → api-key
 * Keep API route names stable for generated mock CRUD helpers.
 */
function toKebabCase(str) {
  return String(str)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[\s_]+/g, '-')
}

/** PascalCase → camelCase with acronym handling. */
function toCamelCase(str) {
  return String(str)
    .replace(/([A-Z]+)([A-Z][a-z])/g, (_m, p1, p2) => p1.charAt(0) + p1.slice(1).toLowerCase() + p2)
    .replace(/^([A-Z]+)$/, m => m.toLowerCase())
    .replace(/^(.)/, m => m.toLowerCase())
}

/** Small English pluralization helper for mock CRUD names. */
function pluralize(word) {
  if (/[^aeiouAEIOU]y$/.test(word)) return word.slice(0, -1) + 'ies'
  if (/(s|x|z|ch|sh)$/i.test(word)) return word + 'es'
  return word + 's'
}

function crudHelperName(entity) {
  // Export CRUD helpers as `pluralize(toCamelCase(entity.name))`:
  //   Customer    → customers
  //   Order       → orders
  //   SLAPolicy   → slaPolicies
  //   APIKey      → apiKeys
  return pluralize(toCamelCase(entity.name))
}

function apiCollectionRoute(entity) {
  const crud = crudHelperName(entity)
  return `// In-memory CRUD for ${entity.name} (collection)
import { NextResponse } from 'next/server'
import { ${crud} } from '@/mock'

export async function GET() {
  return NextResponse.json(await ${crud}.list())
}

export async function POST(req: Request) {
  const body = await req.json()
  const item = await ${crud}.create(body)
  return NextResponse.json(item, { status: 201 })
}
`
}

function apiItemRoute(entity) {
  const crud = crudHelperName(entity)
  // Next.js 16: params is Promise<{...}>, must await it.
  // CRUD helper uses .remove() (not .delete() — JS reserved word).
  return `// In-memory CRUD for ${entity.name} (single by id)
import { NextResponse } from 'next/server'
import { ${crud} } from '@/mock'

type RouteContext = { params: Promise<{ id: string }> }

export async function GET(_: Request, { params }: RouteContext) {
  const { id } = await params
  const item = await ${crud}.get(id)
  if (!item) return NextResponse.json({ error: 'not found' }, { status: 404 })
  return NextResponse.json(item)
}

export async function PATCH(req: Request, { params }: RouteContext) {
  const { id } = await params
  const body = await req.json()
  const item = await ${crud}.update(id, body)
  if (!item) return NextResponse.json({ error: 'not found' }, { status: 404 })
  return NextResponse.json(item)
}

export async function DELETE(_: Request, { params }: RouteContext) {
  const { id } = await params
  const ok = await ${crud}.remove(id)
  if (!ok) return NextResponse.json({ error: 'not found' }, { status: 404 })
  return NextResponse.json({ ok: true })
}
`
}

for (const entity of entities) {
  const kebab = toKebabCase(entity.name)
  const dir = join(outputDir, 'app/api', kebab)
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, 'route.ts'), apiCollectionRoute(entity), 'utf8')

  const dirItem = join(dir, '[id]')
  mkdirSync(dirItem, { recursive: true })
  writeFileSync(join(dirItem, 'route.ts'), apiItemRoute(entity), 'utf8')
}

// ── Done ─────────────────────────────────────────────────────────────────────

const summary = {
  outputDir,
  appName: values.name,
  domain: values.domain,
  entities: entities.map(e => e.name),
  pages: pages.length,
  apiRoutes: entities.length * 2,
  authEnabled: values['with-auth'],
}

process.stdout.write(`\n✓ Scaffold complete\n${JSON.stringify(summary, null, 2)}\n\n`)
process.stdout.write(`Next steps:\n`)
process.stdout.write(`  1. LLM Read forge/src/app/cases/<relevant>/page.tsx for real examples\n`)
process.stdout.write(`  2. LLM Write each app/<route>/page.tsx with real forge API\n`)
process.stdout.write(`  3. cd ${outputDir} && pnpm install --ignore-workspace --ignore-scripts && pnpm dev\n`)
