#!/usr/bin/env node
// 把 src/assets/*.svg 编译成 data URL 字符串常量，写入 src/assets/_inlined.ts。
// 供组件 import 使用，避免组件硬编码外部 public 路径。

import fs from "node:fs";
import path from "node:path";
import url from "node:url";

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), "..");
const ASSETS = path.join(ROOT, "src/assets");
const OUT = path.join(ASSETS, "_inlined.ts");

function toDataUrl(filePath) {
  const buf = fs.readFileSync(filePath);
  return `data:image/svg+xml;base64,${buf.toString("base64")}`;
}

const forgeLogoPath = path.join(ASSETS, "forge-logo.svg");
const fileIconsDir = path.join(ASSETS, "file-icons");

const forgeLogoDataUrl = toDataUrl(forgeLogoPath);

const fileIconEntries = fs
  .readdirSync(fileIconsDir)
  .filter((name) => name.endsWith(".svg"))
  .map((name) => {
    const key = path.basename(name, ".svg");
    const dataUrl = toDataUrl(path.join(fileIconsDir, name));
    return [key, dataUrl];
  })
  .sort(([a], [b]) => a.localeCompare(b));

const lines = [
  "// Generated by scripts/gen-assets.mjs — do not edit.",
  "// Source: src/assets/forge-logo.svg + src/assets/file-icons/*.svg",
  "",
  `export const forgeLogoDataUrl = ${JSON.stringify(forgeLogoDataUrl)};`,
  "",
  "export const fileIconDataUrls: Record<string, string> = {",
  ...fileIconEntries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  "};",
  "",
];

fs.writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${path.relative(ROOT, OUT)} (${fileIconEntries.length} file icons + 1 logo)`);
